import type { ResourceSpec, TestkubeConfig } from "../types/config";

export const APP_VERSION = "2.10";

const resources = (
  reqCpu: string,
  reqMem: string,
  limCpu: string,
  limMem: string
): ResourceSpec => ({
  requestsCpu: reqCpu,
  requestsMemory: reqMem,
  limitsCpu: limCpu,
  limitsMemory: limMem,
});

export const defaultConfig: TestkubeConfig = {
  initial: {
    companyName: "",
    adminEmail: "",
    kubernetesType: "onprem",
    envType: "enterprise-prod",
    licenseMode: "online",
    licenseKey: "",
    licenseSecretRef: "",
    orgsEnvs: [{ id: "org-1", organization: "default", environment: "production" }],
  },
  core: {
    dashboard: true,
    api: true,
    workerService: true,
    ai: false,
  },
  database: {
    type: "mongodb",
    external: false,
    connectionMode: "autogenerated",
    connectionString: "",
    vaultPath: "",
    secretName: "",
    resources: resources("150m", "100Mi", "500m", "512Mi"),
  },
  artifacts: {
    type: "minio",
    external: false,
    connectionMode: "autogenerated",
    endpoint: "",
    bucket: "testkube-artifacts",
    region: "us-east-1",
    accessKeyId: "",
    secretAccessKey: "",
    vaultPath: "",
    secretName: "",
    accessKeyIdKey: "accessKeyId",
    secretAccessKeyKey: "secretAccessKey",
    resources: resources("100m", "256Mi", "500m", "1Gi"),
  },
  nats: {
    embedded: true,
    uri: "nats://testkube-enterprise-nats:4222",
    jetstreamEnabled: true,
    persistent: true,
    storageSize: "10Gi",
    resources: resources("100m", "128Mi", "500m", "1Gi"),
  },
  auth: {
    dexEnabled: true,
    issuerUrl: "",
    connector: "oidc",
    clientId: "",
    clientSecret: "",
    upstreamIssuerUrl: "",
    adminEmails: "",
  },
  endpoints: {
    domain: "",
    uiSubdomain: "dashboard",
    apiSubdomain: "api",
    agentSubdomain: "agent",
    websocketsSubdomain: "websockets",
    storageSubdomain: "storage",
    aiSubdomain: "ai",
    useKubernetesService: false,
    certManager: true,
    certManagerIssuerRef: "letsencrypt-prod",
  },
  advanced: {},
};
