import { stringify } from "yaml";
import {
  isEnterprise,
  type ConnectionMode,
  type ResourceSpec,
  type TestkubeConfig,
} from "../types/config";
import { advancedDefsMap } from "./advancedFields";

type Dict = Record<string, unknown>;

// Sets a value at a dotted path, creating intermediate objects as needed.
function setPath(root: Dict, path: string, value: unknown): void {
  const parts = path.split(".");
  let node = root;
  for (let i = 0; i < parts.length - 1; i++) {
    const key = parts[i];
    if (typeof node[key] !== "object" || node[key] === null || Array.isArray(node[key])) {
      node[key] = {};
    }
    node = node[key] as Dict;
  }
  node[parts[parts.length - 1]] = value;
}

// Merges the per-component "Customize" overrides onto the base values object.
// Only paths that are valid for the current flavor are applied, so switching
// between OSS / Enterprise never leaks stale keys.
function applyAdvanced(base: Dict, cfg: TestkubeConfig): Dict {
  const defs = advancedDefsMap(cfg);
  for (const [path, raw] of Object.entries(cfg.advanced)) {
    const def = defs.get(path);
    if (!def) continue;
    if (raw === "" || raw === undefined || raw === null) continue;
    let value: unknown = raw;
    if (def.type === "number") {
      const n = Number(raw);
      if (Number.isNaN(n)) continue;
      value = n;
    }
    setPath(base, path, value);
  }
  return base;
}

function resourcesToValues(r: ResourceSpec): Dict {
  return {
    requests: { cpu: r.requestsCpu, memory: r.requestsMemory },
    limits: { cpu: r.limitsCpu, memory: r.limitsMemory },
  };
}

// Drops empty strings / empty objects so the rendered values.yaml stays clean.
function prune<T>(value: T): T {
  if (Array.isArray(value)) {
    return value.map((v) => prune(v)) as unknown as T;
  }
  if (value && typeof value === "object") {
    const out: Dict = {};
    for (const [k, v] of Object.entries(value as Dict)) {
      const pruned = prune(v);
      const isEmptyString = pruned === "";
      const isEmptyObject =
        pruned &&
        typeof pruned === "object" &&
        !Array.isArray(pruned) &&
        Object.keys(pruned as Dict).length === 0;
      if (isEmptyString || isEmptyObject || pruned === undefined) continue;
      out[k] = pruned;
    }
    return out as unknown as T;
  }
  return value;
}

function connectionComment(mode: ConnectionMode): string {
  switch (mode) {
    case "autogenerated":
      return "Connection auto-generated by the chart (in-cluster service).";
    case "manual":
      return "Connection provided manually below.";
    case "vault":
      return "Connection sourced from Vault (see annotations / secretRef).";
  }
}

function buildEnterpriseValues(cfg: TestkubeConfig): Dict {
  const { initial, core, database, artifacts, nats, auth, endpoints } = cfg;

  const global: Dict = {
    enterpriseMode: true,
    enterpriseOfflineAccess: initial.licenseMode === "offline",
    enterpriseLicenseKey:
      initial.licenseMode === "online" ? initial.licenseKey : "",
    enterpriseLicenseSecretRef:
      initial.licenseMode === "offline" ? initial.licenseSecretRef : "",
    domain: endpoints.domain,
    uiSubdomain: endpoints.uiSubdomain,
    restApiSubdomain: endpoints.apiSubdomain,
    grpcApiSubdomain: endpoints.agentSubdomain,
    websocketApiSubdomain: endpoints.websocketsSubdomain,
    storageApiSubdomain: endpoints.storageSubdomain,
    aiApiSubdomain: endpoints.aiSubdomain,
    certificateProvider: endpoints.certManager ? "cert-manager" : "",
    certManager: endpoints.certManager
      ? { issuerRef: endpoints.certManagerIssuerRef }
      : {},
    ingress: { enabled: !endpoints.useKubernetesService },
    dex: { issuer: auth.issuerUrl },
    mongo:
      database.type === "mongodb" && database.external
        ? { dsn: database.connectionString }
        : {},
    nats: nats.embedded ? {} : { uri: nats.uri },
    storage: {
      endpoint:
        artifacts.external && artifacts.endpoint ? artifacts.endpoint : "",
      region: artifacts.region,
      accessKeyId: artifacts.accessKeyId,
      secretAccessKey: artifacts.secretAccessKey,
      outputsBucket: artifacts.bucket,
    },
  };

  const values: Dict = {
    global: prune(global),
    minio: { enabled: artifacts.type === "minio" && !artifacts.external },
    mongodb: { enabled: database.type === "mongodb" && !database.external },
    nats: { enabled: nats.embedded },
    "testkube-cloud-ui": { enabled: core.dashboard },
    "testkube-cloud-api": {
      enabled: core.api,
      api: { resources: resourcesToValues(database.resources) },
    },
    "testkube-worker-service": { enabled: core.workerService },
    "testkube-ai-service": { enabled: core.ai },
    dex: {
      enabled: auth.dexEnabled,
      configTemplate: {
        additionalConfig:
          auth.adminEmails.trim().length > 0
            ? `# Static admins: ${auth.adminEmails}`
            : "",
      },
    },
  };

  const result = prune(values);
  // When cert-manager is disabled we must keep an explicit (empty) provider:
  // pruning the empty string would let the chart fall back to its default
  // "cert-manager", which then fails because no issuerRef is set.
  if (!endpoints.certManager) {
    const g = (result.global ?? (result.global = {})) as Dict;
    g.certificateProvider = "";
  }
  return result;
}

function buildOssValues(cfg: TestkubeConfig): Dict {
  const { core, database, artifacts, nats, endpoints } = cfg;
  const mongoInCluster = database.type === "mongodb" && !database.external;
  const pgInCluster = database.type === "postgresql" && !database.external;
  const minioInCluster = artifacts.type === "minio" && !artifacts.external;

  const values: Dict = {
    mongodb: {
      enabled: mongoInCluster,
      ...(mongoInCluster ? { resources: resourcesToValues(database.resources) } : {}),
    },
    postgresql: {
      enabled: pgInCluster,
      ...(pgInCluster ? { resources: resourcesToValues(database.resources) } : {}),
    },
    // NATS subchart config; the subchart is deployed via the
    // `testkube-api.nats.enabled` condition below.
    nats: nats.embedded
      ? {
          config: {
            jetstream: {
              enabled: nats.jetstreamEnabled,
              fileStore: {
                pvc: { enabled: nats.persistent, size: nats.storageSize },
              },
            },
          },
        }
      : {},
    "testkube-api": {
      enabled: core.api,
      uiIngress: {
        enabled: !endpoints.useKubernetesService && core.dashboard,
        host: endpoints.domain
          ? `${endpoints.uiSubdomain}.${endpoints.domain}`
          : "",
      },
      apiIngress: {
        enabled: !endpoints.useKubernetesService,
        host: endpoints.domain
          ? `${endpoints.apiSubdomain}.${endpoints.domain}`
          : "",
      },
      // MinIO lives under the API subchart in the OSS chart.
      minio: minioInCluster
        ? { enabled: true, resources: resourcesToValues(artifacts.resources) }
        : { enabled: false },
      // `enabled` here means "the API uses NATS"; `embedded` runs it in-binary.
      nats: nats.embedded
        ? { enabled: true }
        : { enabled: true, embedded: false, uri: nats.uri },
      mongodb: { enabled: mongoInCluster },
      storage:
        artifacts.type === "minio"
          ? {
              endpoint: artifacts.external ? artifacts.endpoint : "",
              bucket: artifacts.bucket,
              region: artifacts.region,
              accessKeyId:
                artifacts.connectionMode === "manual" ? artifacts.accessKeyId : "",
              accessKey:
                artifacts.connectionMode === "manual"
                  ? artifacts.secretAccessKey
                  : "",
            }
          : {},
    },
    "testkube-operator": { enabled: true },
  };

  return prune(values);
}

export function buildValues(cfg: TestkubeConfig): Dict {
  const base = isEnterprise(cfg.initial.envType)
    ? buildEnterpriseValues(cfg)
    : buildOssValues(cfg);
  return applyAdvanced(base, cfg);
}

export function generateYaml(cfg: TestkubeConfig): string {
  const enterprise = isEnterprise(cfg.initial.envType);
  const orgsEnvs =
    cfg.initial.orgsEnvs
      .map((r) => `${r.organization || "?"}/${r.environment || "?"}`)
      .join(", ") || "(none)";
  const header = [
    "# ---------------------------------------------------------------------------",
    "# Testkube Helm values — generated by the Testkube Initializer",
    `# Company:     ${cfg.initial.companyName || "(not set)"}`,
    `# Admin email: ${cfg.initial.adminEmail || "(not set)"}`,
    `# Flavor:      ${enterprise ? "Enterprise" : "OSS"} (${cfg.initial.envType})`,
    `# Kubernetes:  ${cfg.initial.kubernetesType}`,
    `# License:     ${enterprise ? cfg.initial.licenseMode : "n/a"}`,
    `# Orgs/Envs:   ${orgsEnvs}`,
    `# Database:    ${cfg.database.type}${cfg.database.external ? " (external)" : " (in-cluster)"}`,
    `# Artifacts:   ${cfg.artifacts.type}${cfg.artifacts.external ? " (external)" : " (in-cluster)"} — ${connectionComment(cfg.artifacts.connectionMode)}`,
    `# Chart:       ${enterprise ? "testkube/testkube-enterprise" : "testkube/testkube"}`,
    "# ---------------------------------------------------------------------------",
    "",
  ].join("\n");

  const body = stringify(buildValues(cfg), { indent: 2, lineWidth: 0 });
  return `${header}${body}`;
}

export function downloadYaml(cfg: TestkubeConfig): void {
  const yaml = generateYaml(cfg);
  const blob = new Blob([yaml], { type: "text/yaml;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "values.yaml";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
