import { parse, stringify } from "yaml";
import {
  isEnterprise,
  type ConnectionMode,
  type ResourceSpec,
  type TestkubeConfig,
} from "../types/config";
import { advancedDefsMap } from "./advancedFields";
import {
  buildEnterpriseApiBlock,
  buildEnterpriseApiEnv,
  buildEnterpriseDexBlock,
  buildEnterpriseStorage,
  buildEnterpriseUiBlock,
  dexIssuerUrl,
  ENT_SECRETS,
  minioInCluster,
} from "./enterpriseDefaults";

type Dict = Record<string, unknown>;

// Sets a value at a dotted path, creating intermediate objects as needed.
function setPath(root: Dict, path: string, value: unknown): void {
  const parts = path.split(".");
  let node = root;
  for (let i = 0; i < parts.length - 1; i++) {
    const key = parts[i];
    if (typeof node[key] !== "object" || node[key] === null || Array.isArray(node[key])) {
      node[key] = {};
    }
    node = node[key] as Dict;
  }
  node[parts[parts.length - 1]] = value;
}

// Merges the per-component "Customize" overrides onto the base values object.
// Only paths that are valid for the current flavor are applied, so switching
// between OSS / Enterprise never leaks stale keys.
function applyAdvanced(base: Dict, cfg: TestkubeConfig): Dict {
  const defs = advancedDefsMap(cfg);
  for (const [path, raw] of Object.entries(cfg.advanced)) {
    const def = defs.get(path);
    if (!def) continue;
    if (raw === "" || raw === undefined || raw === null) continue;
    let value: unknown = raw;
    if (def.type === "number") {
      const n = Number(raw);
      if (Number.isNaN(n)) continue;
      value = n;
    } else if (def.type === "yaml") {
      // The field stores raw YAML/JSON text; parse it into structured data.
      try {
        const parsed = parse(String(raw));
        if (parsed === null || parsed === undefined) continue;
        value = parsed;
      } catch {
        continue; // skip invalid YAML rather than breaking the whole document
      }
    }
    setPath(base, path, value);
  }
  return base;
}

function resourcesToValues(r: ResourceSpec): Dict {
  return {
    requests: { cpu: r.requestsCpu, memory: r.requestsMemory },
    limits: { cpu: r.limitsCpu, memory: r.limitsMemory },
  };
}

// Drops empty strings / empty objects so the rendered values.yaml stays clean.
function prune<T>(value: T): T {
  if (Array.isArray(value)) {
    return value.map((v) => prune(v)) as unknown as T;
  }
  if (value && typeof value === "object") {
    const out: Dict = {};
    for (const [k, v] of Object.entries(value as Dict)) {
      const pruned = prune(v);
      const isEmptyString = pruned === "";
      const isEmptyObject =
        pruned &&
        typeof pruned === "object" &&
        !Array.isArray(pruned) &&
        Object.keys(pruned as Dict).length === 0;
      if (isEmptyString || isEmptyObject || pruned === undefined) continue;
      out[k] = pruned;
    }
    return out as unknown as T;
  }
  return value;
}

function connectionComment(mode: ConnectionMode): string {
  switch (mode) {
    case "autogenerated":
      return "Connection auto-generated by the chart (in-cluster service).";
    case "manual":
      return "Connection provided manually below.";
    case "vault":
      return "Connection sourced from Vault (see annotations / secretRef).";
    case "secret":
      return "Credentials referenced from an existing Kubernetes Secret.";
  }
}

function buildEnterpriseValues(cfg: TestkubeConfig): Dict {
  const { initial, core, database, artifacts, nats, auth, endpoints } = cfg;
  const minioCluster = minioInCluster(cfg);

  const global: Dict = {
    enterpriseMode: true,
    enterpriseOfflineAccess: initial.licenseMode === "offline",
    enterpriseLicenseKey:
      initial.licenseMode === "online" ? initial.licenseKey : "",
    enterpriseLicenseSecretRef:
      initial.licenseMode === "offline" ? initial.licenseSecretRef : "",
    domain: endpoints.domain,
    uiSubdomain: endpoints.uiSubdomain,
    restApiSubdomain: endpoints.apiSubdomain,
    grpcApiSubdomain: endpoints.agentSubdomain,
    websocketApiSubdomain: endpoints.websocketsSubdomain,
    storageApiSubdomain: endpoints.storageSubdomain,
    aiApiSubdomain: endpoints.aiSubdomain,
    certificateProvider: endpoints.certManager ? "cert-manager" : "",
    certManager: endpoints.certManager
      ? { issuerRef: endpoints.certManagerIssuerRef }
      : {},
    ingress: { enabled: !endpoints.useKubernetesService },
    dex: { issuer: auth.dexEnabled ? dexIssuerUrl(cfg) : auth.issuerUrl },
    credentials: {
      masterPassword: {
        secretKeyRef: { name: ENT_SECRETS.master, key: "password" },
      },
    },
    mongo:
      database.type === "mongodb" && database.external
        ? database.connectionMode === "secret"
          ? { dsnSecretRef: database.secretName }
          : { dsn: database.connectionString }
        : {},
    nats: nats.embedded ? {} : { uri: nats.uri },
    storage: buildEnterpriseStorage(cfg),
  };

  const apiEnv = buildEnterpriseApiEnv(cfg);

  const values: Dict = {
    global: prune(global),
    sharedSecretGenerator: { enabled: true },
    minio: {
      enabled: minioCluster,
      ...(minioCluster && artifacts.connectionMode === "autogenerated"
        ? { auth: { existingSecret: ENT_SECRETS.minio } }
        : {}),
    },
    mongodb: { enabled: database.type === "mongodb" && !database.external },
    nats: {
      enabled: nats.embedded,
      config: { cluster: { enabled: false } },
    },
    "testkube-cloud-ui": {
      enabled: core.dashboard,
      ...buildEnterpriseUiBlock(cfg),
    },
    "testkube-cloud-api": {
      enabled: core.api,
      api: {
        resources: resourcesToValues(database.resources),
        ...buildEnterpriseApiBlock(cfg),
      },
      ...(Object.keys(apiEnv).length > 0 ? { additionalEnv: apiEnv } : {}),
      prometheus: { enabled: false },
    },
    "testkube-worker-service": {
      enabled: core.workerService,
      ...(minioCluster ? { additionalEnv: { USE_MINIO: true } } : {}),
    },
    "testkube-ai-service": { enabled: core.ai },
    dex: buildEnterpriseDexBlock(cfg),
  };

  const result = prune(values);
  // When cert-manager is disabled we must keep an explicit (empty) provider:
  // pruning the empty string would let the chart fall back to its default
  // "cert-manager", which then fails because no issuerRef is set.
  if (!endpoints.certManager) {
    const g = (result.global ?? (result.global = {})) as Dict;
    g.certificateProvider = "";
  }
  return result;
}

function buildOssValues(cfg: TestkubeConfig): Dict {
  const { core, database, artifacts, nats, endpoints } = cfg;
  const mongoInCluster = database.type === "mongodb" && !database.external;
  const pgInCluster = database.type === "postgresql" && !database.external;
  const minioInCluster = artifacts.type === "minio" && !artifacts.external;

  const values: Dict = {
    mongodb: {
      enabled: mongoInCluster,
      ...(mongoInCluster ? { resources: resourcesToValues(database.resources) } : {}),
    },
    postgresql: {
      enabled: pgInCluster,
      ...(pgInCluster ? { resources: resourcesToValues(database.resources) } : {}),
    },
    // NATS subchart config; the subchart is deployed via the
    // `testkube-api.nats.enabled` condition below.
    nats: nats.embedded
      ? {
          config: {
            jetstream: {
              enabled: nats.jetstreamEnabled,
              fileStore: {
                pvc: { enabled: nats.persistent, size: nats.storageSize },
              },
            },
          },
        }
      : {},
    "testkube-api": {
      enabled: core.api,
      uiIngress: {
        enabled: !endpoints.useKubernetesService && core.dashboard,
        host: endpoints.domain
          ? `${endpoints.uiSubdomain}.${endpoints.domain}`
          : "",
      },
      apiIngress: {
        enabled: !endpoints.useKubernetesService,
        host: endpoints.domain
          ? `${endpoints.apiSubdomain}.${endpoints.domain}`
          : "",
      },
      // MinIO lives under the API subchart in the OSS chart.
      minio: minioInCluster
        ? { enabled: true, resources: resourcesToValues(artifacts.resources) }
        : { enabled: false },
      // `enabled` here means "the API uses NATS"; `embedded` runs it in-binary.
      nats: nats.embedded
        ? { enabled: true }
        : { enabled: true, embedded: false, uri: nats.uri },
      mongodb: { enabled: mongoInCluster },
      storage: {
        endpoint: artifacts.external ? artifacts.endpoint : "",
        bucket: artifacts.bucket,
        region: artifacts.region,
        ...(artifacts.connectionMode === "manual"
          ? {
              accessKeyId: artifacts.accessKeyId,
              accessKey: artifacts.secretAccessKey,
            }
          : {}),
        ...(artifacts.connectionMode === "secret"
          ? {
              secretNameAccessKeyId: artifacts.secretName,
              secretKeyAccessKeyId: artifacts.accessKeyIdKey,
              secretNameSecretAccessKey: artifacts.secretName,
              secretKeySecretAccessKey: artifacts.secretAccessKeyKey,
            }
          : {}),
      },
    },
    "testkube-operator": { enabled: true },
  };

  return prune(values);
}

export function buildValues(cfg: TestkubeConfig): Dict {
  const base = isEnterprise(cfg.initial.envType)
    ? buildEnterpriseValues(cfg)
    : buildOssValues(cfg);
  return applyAdvanced(base, cfg);
}

export function generateYaml(cfg: TestkubeConfig): string {
  const enterprise = isEnterprise(cfg.initial.envType);
  const orgsEnvs =
    cfg.initial.orgsEnvs
      .map((r) => `${r.organization || "?"}/${r.environment || "?"}`)
      .join(", ") || "(none)";
  const header = [
    "# ---------------------------------------------------------------------------",
    "# Testkube Helm values — generated by the Testkube Initializer",
    `# Company:     ${cfg.initial.companyName || "(not set)"}`,
    `# Admin email: ${cfg.initial.adminEmail || "(not set)"}`,
    `# Flavor:      ${enterprise ? "Enterprise" : "OSS"} (${cfg.initial.envType})`,
    `# Kubernetes:  ${cfg.initial.kubernetesType}`,
    `# License:     ${enterprise ? cfg.initial.licenseMode : "n/a"}`,
    `# Orgs/Envs:   ${orgsEnvs}`,
    `# Database:    ${cfg.database.type}${cfg.database.external ? " (external)" : " (in-cluster)"}`,
    `# Artifacts:   ${cfg.artifacts.type}${cfg.artifacts.external ? " (external)" : " (in-cluster)"} — ${connectionComment(cfg.artifacts.connectionMode)}`,
    `# Chart:       ${enterprise ? "testkube/testkube-enterprise" : "testkube/testkube"}`,
    "# ---------------------------------------------------------------------------",
    "",
  ].join("\n");

  const body = stringify(buildValues(cfg), { indent: 2, lineWidth: 0 });
  return `${header}${body}`;
}

export function downloadYaml(cfg: TestkubeConfig): void {
  download("values.yaml", generateYaml(cfg));
}

function download(filename: string, contents: string): void {
  const blob = new Blob([contents], { type: "text/yaml;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ---------------------------------------------------------------------------
// Secrets handling
// ---------------------------------------------------------------------------

export interface PlaintextSecret {
  label: string;
  hint: string;
}

// Inline (plaintext) secrets that will be written into values.yaml as-is.
// Used to warn the user and nudge them toward "Existing Secret" mode.
export function detectPlaintextSecrets(cfg: TestkubeConfig): PlaintextSecret[] {
  const enterprise = isEnterprise(cfg.initial.envType);
  const out: PlaintextSecret[] = [];

  if (enterprise && cfg.initial.licenseMode === "online" && cfg.initial.licenseKey) {
    out.push({
      label: "Enterprise license key",
      hint: "global.enterpriseLicenseKey — consider Offline mode with a secret ref.",
    });
  }
  if (cfg.artifacts.connectionMode === "manual" && (cfg.artifacts.accessKeyId || cfg.artifacts.secretAccessKey)) {
    out.push({
      label: "Object storage access key / secret",
      hint: "Switch the Artifacts credentials source to \"Existing Secret\".",
    });
  }
  if (cfg.database.external && cfg.database.connectionMode === "manual" && cfg.database.connectionString) {
    out.push({
      label: "Database connection string",
      hint: "Switch the Database connection source to \"Existing Secret\".",
    });
  }
  if (enterprise && cfg.auth.dexEnabled && cfg.auth.clientSecret) {
    out.push({
      label: "OIDC/Dex client secret",
      hint: "auth client secret is written in plaintext.",
    });
  }
  return out;
}

interface SecretSkeleton {
  name: string;
  keys: string[];
}

// Kubernetes Secrets referenced via "Existing Secret" mode, that the user must
// create before installing. We emit a skeleton manifest with placeholders.
export function referencedSecrets(cfg: TestkubeConfig): SecretSkeleton[] {
  const enterprise = isEnterprise(cfg.initial.envType);
  const out: SecretSkeleton[] = [];

  if (cfg.artifacts.connectionMode === "secret" && cfg.artifacts.secretName) {
    out.push(
      enterprise
        ? { name: cfg.artifacts.secretName, keys: ["root-user", "root-password", "token"] }
        : {
            name: cfg.artifacts.secretName,
            keys: [cfg.artifacts.accessKeyIdKey, cfg.artifacts.secretAccessKeyKey],
          }
    );
  }
  if (
    enterprise &&
    cfg.database.external &&
    cfg.database.connectionMode === "secret" &&
    cfg.database.secretName
  ) {
    out.push({ name: cfg.database.secretName, keys: ["MONGO_DSN"] });
  }
  return out;
}

export function generateSecretsYaml(cfg: TestkubeConfig): string {
  const secrets = referencedSecrets(cfg);
  if (secrets.length === 0) {
    return "# No 'Existing Secret' references configured.\n# Use the \"Existing Secret\" credential source in Artifacts/Database to populate this file.\n";
  }
  const header = [
    "# ---------------------------------------------------------------------------",
    "# Kubernetes Secrets referenced by your values.yaml.",
    "# Replace the REPLACE_ME placeholders and apply BEFORE installing the chart:",
    "#   kubectl apply -n <namespace> -f secrets.yaml",
    "# ---------------------------------------------------------------------------",
    "",
  ].join("\n");

  const docs = secrets.map((s) => {
    const data = s.keys.map((k) => `  ${k}: "REPLACE_ME"`).join("\n");
    return [
      "apiVersion: v1",
      "kind: Secret",
      "metadata:",
      `  name: ${s.name}`,
      "type: Opaque",
      "stringData:",
      data,
    ].join("\n");
  });

  return `${header}${docs.join("\n---\n")}\n`;
}

export function downloadSecrets(cfg: TestkubeConfig): void {
  download("secrets.yaml", generateSecretsYaml(cfg));
}
