import { Card, Field, ResourceEditor, SegmentedControl, TextInput, Toggle } from "../components/ui";
import CustomizePanel from "../components/CustomizePanel";
import type { ArtifactStoreType, ConnectionMode } from "../types/config";
import type { StepProps } from "./types";

export default function ArtifactsStoreStep({ config, update, setAdvanced }: StepProps) {
  const c = config.artifacts;
  return (
    <div className="space-y-5">
      <Card title="Store">
        <Field label="Store Type">
          <SegmentedControl<ArtifactStoreType>
            value={c.type}
            onChange={(v) => update("artifacts", { type: v })}
            options={[
              { value: "seaweedfs", label: "SeaweedFS" },
              { value: "s3", label: "AWS S3" },
              { value: "minio", label: "MinIO" },
            ]}
          />
        </Field>
        <Toggle
          label="Is it external?"
          description="Use a managed / external S3-compatible endpoint."
          checked={c.external}
          onChange={(v) => update("artifacts", { external: v })}
        />
      </Card>

      <Card title="Connection">
        <Field label="Credentials source">
          <SegmentedControl<ConnectionMode>
            value={c.connectionMode}
            onChange={(v) => update("artifacts", { connectionMode: v })}
            options={[
              { value: "autogenerated", label: "Autogenerated" },
              { value: "manual", label: "Manual" },
              { value: "vault", label: "From Vault" },
            ]}
          />
        </Field>
        <div className="grid gap-4 sm:grid-cols-2">
          <Field label="Bucket">
            <TextInput
              value={c.bucket}
              onChange={(e) => update("artifacts", { bucket: e.target.value })}
            />
          </Field>
          <Field label="Region">
            <TextInput
              value={c.region}
              onChange={(e) => update("artifacts", { region: e.target.value })}
            />
          </Field>
        </div>
        {c.external && (
          <Field label="Endpoint" hint="S3-compatible endpoint without protocol.">
            <TextInput
              placeholder="s3.amazonaws.com"
              value={c.endpoint}
              onChange={(e) => update("artifacts", { endpoint: e.target.value })}
            />
          </Field>
        )}
        {c.connectionMode === "manual" && (
          <div className="grid gap-4 sm:grid-cols-2">
            <Field label="Access Key ID">
              <TextInput
                value={c.accessKeyId}
                onChange={(e) => update("artifacts", { accessKeyId: e.target.value })}
              />
            </Field>
            <Field label="Secret Access Key">
              <TextInput
                type="password"
                value={c.secretAccessKey}
                onChange={(e) =>
                  update("artifacts", { secretAccessKey: e.target.value })
                }
              />
            </Field>
          </div>
        )}
        {c.connectionMode === "vault" && (
          <Field label="Vault path">
            <TextInput
              placeholder="secret/data/testkube/storage"
              value={c.vaultPath}
              onChange={(e) => update("artifacts", { vaultPath: e.target.value })}
            />
          </Field>
        )}
      </Card>

      {!c.external && (
        <Card title="Resources">
          <ResourceEditor
            value={c.resources}
            onChange={(patch) =>
              update("artifacts", { resources: { ...c.resources, ...patch } })
            }
          />
        </Card>
      )}

      <CustomizePanel stepId="artifacts" config={config} setAdvanced={setAdvanced} />
    </div>
  );
}
