import { Card, Field, ResourceEditor, SegmentedControl, TextInput, Toggle } from "../components/ui";
import CustomizePanel from "../components/CustomizePanel";
import { tipFor } from "../lib/tips";
import type { ArtifactStoreType, ConnectionMode } from "../types/config";
import type { StepProps } from "./types";

export default function ArtifactsStoreStep({ config, update, setAdvanced }: StepProps) {
  const c = config.artifacts;
  const env = config.initial.envType;
  const t = (path: string, fallback: string) => tipFor(env, path) ?? fallback;
  return (
    <div className="space-y-5">
      <Card title="Store">
        <Field
          label="Store Type"
          help="Object-storage backend for logs and artifacts: SeaweedFS or MinIO run in-cluster; AWS S3 uses a managed/external endpoint."
        >
          <SegmentedControl<ArtifactStoreType>
            value={c.type}
            onChange={(v) => update("artifacts", { type: v })}
            options={[
              { value: "seaweedfs", label: "SeaweedFS" },
              { value: "s3", label: "AWS S3" },
              { value: "minio", label: "MinIO" },
            ]}
          />
        </Field>
        <Toggle
          label="Is it external?"
          description="Use a managed / external S3-compatible endpoint."
          help="When enabled, Testkube connects to your own S3-compatible storage instead of deploying one in the cluster."
          checked={c.external}
          onChange={(v) => update("artifacts", { external: v })}
        />
      </Card>

      <Card title="Connection">
        <Field
          label="Credentials source"
          help="How storage credentials are provided: auto-generated by the chart, entered manually here, or pulled from Vault at deploy time."
        >
          <SegmentedControl<ConnectionMode>
            value={c.connectionMode}
            onChange={(v) => update("artifacts", { connectionMode: v })}
            options={[
              { value: "autogenerated", label: "Autogenerated" },
              { value: "manual", label: "Manual" },
              { value: "secret", label: "Existing Secret" },
              { value: "vault", label: "From Vault" },
            ]}
          />
        </Field>
        <div className="grid gap-4 sm:grid-cols-2">
          <Field
            label="Bucket"
            help={t(
              "global.storage.outputsBucket",
              "Object-storage bucket where test artifacts and logs are stored."
            )}
            helpPath="global.storage.outputsBucket"
          >
            <TextInput
              value={c.bucket}
              onChange={(e) => update("artifacts", { bucket: e.target.value })}
            />
          </Field>
          <Field
            label="Region"
            help={t("global.storage.region", "Region of the S3-compatible storage (e.g. us-east-1).")}
            helpPath="global.storage.region"
          >
            <TextInput
              value={c.region}
              onChange={(e) => update("artifacts", { region: e.target.value })}
            />
          </Field>
        </div>
        {c.external && (
          <Field
            label="Endpoint"
            hint="S3-compatible endpoint without protocol."
            help={t(
              "global.storage.endpoint",
              "Endpoint to a S3-compatible storage service (without protocol)."
            )}
            helpPath="global.storage.endpoint"
          >
            <TextInput
              placeholder="s3.amazonaws.com"
              value={c.endpoint}
              onChange={(e) => update("artifacts", { endpoint: e.target.value })}
            />
          </Field>
        )}
        {c.connectionMode === "manual" && (
          <div className="grid gap-4 sm:grid-cols-2">
            <Field
              label="Access Key ID"
              help={t("global.storage.accessKeyId", "S3 Access Key ID used to authenticate to the storage service.")}
              helpPath="global.storage.accessKeyId"
            >
              <TextInput
                value={c.accessKeyId}
                onChange={(e) => update("artifacts", { accessKeyId: e.target.value })}
              />
            </Field>
            <Field
              label="Secret Access Key"
              help={t("global.storage.secretAccessKey", "S3 Secret Access Key paired with the Access Key ID.")}
              helpPath="global.storage.secretAccessKey"
            >
              <TextInput
                type="password"
                value={c.secretAccessKey}
                onChange={(e) =>
                  update("artifacts", { secretAccessKey: e.target.value })
                }
              />
            </Field>
          </div>
        )}
        {c.connectionMode === "secret" && (
          <>
            <Field
              label="Secret name"
              help="Name of an existing Kubernetes Secret holding the storage credentials. Keeps secrets out of values.yaml."
            >
              <TextInput
                placeholder="testkube-storage-credentials"
                value={c.secretName}
                onChange={(e) => update("artifacts", { secretName: e.target.value })}
              />
            </Field>
            {config.initial.envType === "oss" && (
              <div className="grid gap-4 sm:grid-cols-2">
                <Field
                  label="Access Key ID — secret key"
                  help="Key inside the Secret that holds the access key ID."
                >
                  <TextInput
                    value={c.accessKeyIdKey}
                    onChange={(e) =>
                      update("artifacts", { accessKeyIdKey: e.target.value })
                    }
                  />
                </Field>
                <Field
                  label="Secret Access Key — secret key"
                  help="Key inside the Secret that holds the secret access key."
                >
                  <TextInput
                    value={c.secretAccessKeyKey}
                    onChange={(e) =>
                      update("artifacts", { secretAccessKeyKey: e.target.value })
                    }
                  />
                </Field>
              </div>
            )}
            {config.initial.envType !== "oss" && (
              <p className="text-xs text-tk-purple-200/70">
                The Secret must contain keys{" "}
                <code className="text-tk-pink">root-user</code>,{" "}
                <code className="text-tk-pink">root-password</code> and{" "}
                <code className="text-tk-pink">token</code>.
              </p>
            )}
          </>
        )}
        {c.connectionMode === "vault" && (
          <Field
            label="Vault path"
            help="Vault secret path resolved at deploy time to inject the storage credentials."
          >
            <TextInput
              placeholder="secret/data/testkube/storage"
              value={c.vaultPath}
              onChange={(e) => update("artifacts", { vaultPath: e.target.value })}
            />
          </Field>
        )}
      </Card>

      {!c.external && (
        <Card title="Resources">
          <ResourceEditor
            value={c.resources}
            onChange={(patch) =>
              update("artifacts", { resources: { ...c.resources, ...patch } })
            }
          />
        </Card>
      )}

      <CustomizePanel stepId="artifacts" config={config} setAdvanced={setAdvanced} />
    </div>
  );
}
