import { Card, Field, ResourceEditor, SegmentedControl, TextInput, Toggle } from "../components/ui";
import CustomizePanel from "../components/CustomizePanel";
import type { ConnectionMode, DatabaseType } from "../types/config";
import type { StepProps } from "./types";

export default function DatabaseStep({ config, update, setAdvanced }: StepProps) {
  const c = config.database;
  return (
    <div className="space-y-5">
      <Card title="Engine">
        <Field label="Database Type">
          <SegmentedControl<DatabaseType>
            value={c.type}
            onChange={(v) => update("database", { type: v })}
            options={[
              { value: "mongodb", label: "MongoDB" },
              { value: "postgresql", label: "PostgreSQL" },
            ]}
          />
        </Field>
        <Toggle
          label="Is it external?"
          description="Use a managed database instead of an in-cluster instance."
          checked={c.external}
          onChange={(v) => update("database", { external: v })}
        />
      </Card>

      {c.external && (
        <Card title="Connection">
          <Field label="Connection String source">
            <SegmentedControl<ConnectionMode>
              value={c.connectionMode}
              onChange={(v) => update("database", { connectionMode: v })}
              options={[
                { value: "autogenerated", label: "Autogenerated" },
                { value: "manual", label: "Manual" },
                { value: "vault", label: "From Vault" },
              ]}
            />
          </Field>
          {c.connectionMode === "manual" && (
            <Field label="Connection String">
              <TextInput
                placeholder={
                  c.type === "mongodb"
                    ? "mongodb://user:pass@host:27017/db"
                    : "postgres://user:pass@host:5432/db"
                }
                value={c.connectionString}
                onChange={(e) => update("database", { connectionString: e.target.value })}
              />
            </Field>
          )}
          {c.connectionMode === "vault" && (
            <Field label="Vault path" hint="Path/secret reference resolved at deploy time.">
              <TextInput
                placeholder="secret/data/testkube/db"
                value={c.vaultPath}
                onChange={(e) => update("database", { vaultPath: e.target.value })}
              />
            </Field>
          )}
        </Card>
      )}

      {!c.external && (
        <Card title="Resources">
          <ResourceEditor
            value={c.resources}
            onChange={(patch) =>
              update("database", { resources: { ...c.resources, ...patch } })
            }
          />
        </Card>
      )}

      <CustomizePanel stepId="database" config={config} setAdvanced={setAdvanced} />
    </div>
  );
}
