import { Card, Field, ResourceEditor, SegmentedControl, TextInput, Toggle } from "../components/ui";
import CustomizePanel from "../components/CustomizePanel";
import { tipFor } from "../lib/tips";
import { isEnterprise, type ConnectionMode, type DatabaseType } from "../types/config";
import type { StepProps } from "./types";

export default function DatabaseStep({ config, update, setAdvanced }: StepProps) {
  const c = config.database;
  const env = config.initial.envType;
  const t = (path: string, fallback: string) => tipFor(env, path) ?? fallback;
  return (
    <div className="space-y-5">
      <Card title="Engine">
        <Field
          label="Database Type"
          help="Backend store for test results and history. MongoDB is the default; PostgreSQL is also supported."
        >
          <SegmentedControl<DatabaseType>
            value={c.type}
            onChange={(v) => update("database", { type: v })}
            options={[
              { value: "mongodb", label: "MongoDB" },
              { value: "postgresql", label: "PostgreSQL" },
            ]}
          />
        </Field>
        <Toggle
          label="Is it external?"
          description="Use a managed database instead of an in-cluster instance."
          help="When enabled, Testkube connects to your managed database via the connection string below instead of deploying one in-cluster."
          checked={c.external}
          onChange={(v) =>
            update("database", {
              external: v,
              // Autogenerated is only valid for in-cluster; default external to Manual.
              ...(v && c.connectionMode !== "secret"
                ? { connectionMode: "manual" as ConnectionMode }
                : {}),
            })
          }
        />
      </Card>

      {c.external && (
        <Card title="Connection">
          <Field
            label="Connection String source"
            help="How the database connection string is supplied: auto-generated, entered manually, or pulled from Vault at deploy time."
          >
            <SegmentedControl<ConnectionMode>
              value={c.connectionMode}
              onChange={(v) => update("database", { connectionMode: v })}
              options={[
                { value: "manual", label: "Manual" },
                { value: "secret", label: "Existing Secret" },
              ]}
            />
          </Field>
          {c.connectionMode === "secret" && (
            <Field
              label="Secret name"
              hint={
                isEnterprise(config.initial.envType)
                  ? "Secret must contain key MONGO_DSN."
                  : c.type === "mongodb"
                    ? "Secret must contain key mongo-dsn."
                    : "Secret must contain key postgres-dsn."
              }
              help={t(
                "global.mongo.dsnSecretRef",
                "Existing Kubernetes Secret holding the database DSN."
              )}
              helpPath={
                isEnterprise(config.initial.envType) ? "global.mongo.dsnSecretRef" : undefined
              }
            >
              <TextInput
                placeholder="testkube-mongo-dsn"
                value={c.secretName}
                onChange={(e) => update("database", { secretName: e.target.value })}
              />
            </Field>
          )}
          {c.connectionMode === "manual" && (
            <Field
              label="Connection String"
              help={t(
                "global.mongo.dsn",
                "Full database connection string (DSN) Testkube uses to reach your external database."
              )}
              helpPath={c.type === "mongodb" ? "global.mongo.dsn" : undefined}
            >
              <TextInput
                placeholder={
                  c.type === "mongodb"
                    ? "mongodb://user:pass@host:27017/db"
                    : "postgres://user:pass@host:5432/db"
                }
                value={c.connectionString}
                onChange={(e) => update("database", { connectionString: e.target.value })}
              />
            </Field>
          )}
        </Card>
      )}

      {!c.external && (
        <Card title="Resources">
          <ResourceEditor
            value={c.resources}
            onChange={(patch) =>
              update("database", { resources: { ...c.resources, ...patch } })
            }
          />
        </Card>
      )}

      <CustomizePanel stepId="database" config={config} setAdvanced={setAdvanced} />
    </div>
  );
}
