// Central configuration model for the Testkube Helm Values Initializer.
// The wizard collects these high-level decisions and the YAML generator
// (src/lib/yaml.ts) maps them onto the real Helm chart keys for either the
// OSS chart (testkube/testkube) or the Enterprise chart (testkube-enterprise).

export type KubernetesType = "onprem" | "cloud";

// Deployment flavor. Drives whether we render the OSS or Enterprise values.
export type EnvType = "oss" | "enterprise-prod" | "enterprise-lab";

export type LicenseMode = "online" | "offline";

export type DatabaseType = "mongodb" | "postgresql";

export type ArtifactStoreType = "seaweedfs" | "s3" | "minio";

// How a connection string / credentials get supplied.
export type ConnectionMode = "autogenerated" | "manual" | "vault" | "secret";

export type AuthConnectorType = "oidc" | "google" | "github" | "gitlab" | "ldap";

export interface ResourceSpec {
  requestsCpu: string;
  requestsMemory: string;
  limitsCpu: string;
  limitsMemory: string;
}

export interface OrgEnvRow {
  id: string;
  organization: string;
  environment: string;
}

export interface InitialConfig {
  companyName: string;
  adminEmail: string;
  kubernetesType: KubernetesType;
  envType: EnvType;
  licenseMode: LicenseMode;
  licenseKey: string;
  // For offline licenses the key is mounted through a secret reference.
  licenseSecretRef: string;
  orgsEnvs: OrgEnvRow[];
}

export interface CoreComponents {
  dashboard: boolean;
  api: boolean;
  workerService: boolean;
  ai: boolean;
}

export interface DatabaseConfig {
  type: DatabaseType;
  external: boolean;
  connectionMode: ConnectionMode;
  connectionString: string;
  vaultPath: string;
  // "Existing Secret" mode: secret holding the connection string (DSN).
  secretName: string;
  resources: ResourceSpec;
}

export interface ArtifactsStoreConfig {
  type: ArtifactStoreType;
  external: boolean;
  connectionMode: ConnectionMode;
  endpoint: string;
  bucket: string;
  region: string;
  accessKeyId: string;
  secretAccessKey: string;
  vaultPath: string;
  // "Existing Secret" mode: reference a pre-created Kubernetes Secret.
  secretName: string;
  accessKeyIdKey: string;
  secretAccessKeyKey: string;
  resources: ResourceSpec;
}

export interface NatsConfig {
  embedded: boolean;
  uri: string;
  jetstreamEnabled: boolean;
  persistent: boolean;
  storageSize: string;
  resources: ResourceSpec;
}

export interface AuthConfig {
  // Dex is the identity broker used by Testkube Enterprise.
  dexEnabled: boolean;
  issuerUrl: string;
  connector: AuthConnectorType;
  clientId: string;
  clientSecret: string;
  adminEmails: string;
}

export interface EndpointsConfig {
  domain: string;
  uiSubdomain: string;
  apiSubdomain: string;
  agentSubdomain: string;
  websocketsSubdomain: string;
  storageSubdomain: string;
  aiSubdomain: string;
  useKubernetesService: boolean;
  certManager: boolean;
  certManagerIssuerRef: string;
}

// Scalar value for an advanced override (keyed by its real dotted chart path).
export type AdvancedScalar = string | boolean;

export interface TestkubeConfig {
  initial: InitialConfig;
  core: CoreComponents;
  database: DatabaseConfig;
  artifacts: ArtifactsStoreConfig;
  nats: NatsConfig;
  auth: AuthConfig;
  endpoints: EndpointsConfig;
  // Advanced overrides set from the per-component "Customize" panels.
  // Keys are the exact dotted Helm value paths (e.g. "testkube-api.replicaCount").
  advanced: Record<string, AdvancedScalar>;
}

export const isEnterprise = (env: EnvType): boolean =>
  env === "enterprise-prod" || env === "enterprise-lab";
