// Central configuration model for the Testkube Helm Values Initializer.
// The wizard collects these high-level decisions and the YAML generator
// (src/lib/yaml.ts) maps them onto the real Helm chart keys for either the
// OSS chart (testkube/testkube) or the Enterprise chart (testkube-enterprise).

export type KubernetesType = "onprem" | "cloud";

// Deployment flavor. Drives whether we render the OSS or Enterprise values.
export type EnvType = "oss" | "enterprise-prod" | "enterprise-lab";

export type LicenseMode = "online" | "offline";

export type DatabaseType = "mongodb" | "postgresql";

export type ArtifactStoreType = "seaweedfs" | "s3" | "minio";

// How public endpoints are exposed: classic Ingress or Gateway API (chart >= 2.11).
export type ExposureMode = "ingress" | "gateway";

// How a connection string / credentials get supplied.
export type ConnectionMode = "autogenerated" | "manual" | "vault" | "secret";

export type AuthConnectorType = "oidc" | "google" | "github" | "gitlab" | "ldap";

// LLM provider preset for the AI service — used to prefill the base URL / models.
export type AiProviderPreset = "openai" | "azure-openai" | "custom";

// How the LLM API key is supplied to the AI service.
export type AiCredentialSource = "inline" | "secret";

// Where the AI service stores its state (PostgreSQL is required).
export type AiPostgresMode = "in-cluster" | "external";

export interface ResourceSpec {
  requestsCpu: string;
  requestsMemory: string;
  limitsCpu: string;
  limitsMemory: string;
}

export interface OrgEnvRow {
  id: string;
  organization: string;
  environment: string;
}

export interface InitialConfig {
  companyName: string;
  adminEmail: string;
  kubernetesType: KubernetesType;
  envType: EnvType;
  licenseMode: LicenseMode;
  licenseKey: string;
  // For offline licenses the key is mounted through a secret reference.
  licenseSecretRef: string;
  orgsEnvs: OrgEnvRow[];
}

export interface CoreComponents {
  dashboard: boolean;
  api: boolean;
  workerService: boolean;
  ai: boolean;
}

export interface DatabaseConfig {
  type: DatabaseType;
  external: boolean;
  connectionMode: ConnectionMode;
  connectionString: string;
  vaultPath: string;
  // "Existing Secret" mode: secret holding the connection string (DSN).
  secretName: string;
  resources: ResourceSpec;
}

export interface ArtifactsStoreConfig {
  type: ArtifactStoreType;
  external: boolean;
  connectionMode: ConnectionMode;
  endpoint: string;
  bucket: string;
  region: string;
  accessKeyId: string;
  secretAccessKey: string;
  vaultPath: string;
  // "Existing Secret" mode: reference a pre-created Kubernetes Secret.
  secretName: string;
  accessKeyIdKey: string;
  secretAccessKeyKey: string;
  // Helm release name — used to build the in-cluster SeaweedFS filer endpoint
  // (<release>-seaweedfs-filer:8333), which is release-name dependent.
  seaweedfsReleaseName: string;
  resources: ResourceSpec;
}

export interface NatsConfig {
  embedded: boolean;
  uri: string;
  jetstreamEnabled: boolean;
  persistent: boolean;
  storageSize: string;
  resources: ResourceSpec;
}

// AI service configuration. Maps onto the modern unified `inference:` schema of
// the testkube-ai-service subchart (chart >= 2.10) plus its PostgreSQL dependency.
export interface AiConfig {
  // Prefills base URL / model defaults for the chosen LLM vendor.
  provider: AiProviderPreset;
  // inference.defaults.url — base URL of the OpenAI-compatible LLM endpoint.
  baseUrl: string;
  // inference.agent[0].model — reasoning model used by the assistant.
  agentModel: string;
  // inference.tasks.model — lightweight model for titles/classification (optional).
  tasksModel: string;
  // inference.embeddings.model — embeddings model for vector search (optional, omit disables).
  embeddingsModel: string;
  // Whether the LLM API key is written inline or referenced from a Secret.
  credentialSource: AiCredentialSource;
  // inference.defaults.apiKey (inline mode).
  apiKey: string;
  // inference.defaults.secretRef / secretRefKey (secret mode).
  apiKeySecretRef: string;
  apiKeySecretKey: string;
  // AI service PostgreSQL backing store.
  postgresMode: AiPostgresMode;
  // External Postgres DSN (global.postgres.dsn) or secret ref (global.postgres.dsnSecretRef).
  postgresDsn: string;
  postgresDsnSecretRef: string;
  postgresDsnSecretKey: string;
}

export interface AuthConfig {
  // Dex is the identity broker used by Testkube Enterprise.
  dexEnabled: boolean;
  // Public Dex issuer URL (what browsers / the API use).
  issuerUrl: string;
  connector: AuthConnectorType;
  // Upstream IdP OAuth client credentials (fed through Dex).
  clientId: string;
  clientSecret: string;
  // Upstream OIDC issuer (e.g. https://accounts.google.com) — not the Dex URL.
  upstreamIssuerUrl: string;
  adminEmails: string;
}

export interface EndpointsConfig {
  domain: string;
  uiSubdomain: string;
  apiSubdomain: string;
  agentSubdomain: string;
  websocketsSubdomain: string;
  storageSubdomain: string;
  aiSubdomain: string;
  useKubernetesService: boolean;
  certManager: boolean;
  certManagerIssuerRef: string;
  // Public exposure mechanism (Ingress vs Gateway API). Enterprise only.
  exposureMode: ExposureMode;
  // GatewayClass provided by the installed controller (e.g. "traefik", "nginx").
  gatewayClassName: string;
  // Whether the chart creates the Gateway resource or attaches to an existing one.
  gatewayCreate: boolean;
}

// Scalar value for an advanced override (keyed by its real dotted chart path).
export type AdvancedScalar = string | boolean;

export interface TestkubeConfig {
  initial: InitialConfig;
  core: CoreComponents;
  database: DatabaseConfig;
  artifacts: ArtifactsStoreConfig;
  nats: NatsConfig;
  ai: AiConfig;
  auth: AuthConfig;
  endpoints: EndpointsConfig;
  // Advanced overrides set from the per-component "Customize" panels.
  // Keys are the exact dotted Helm value paths (e.g. "testkube-api.replicaCount").
  advanced: Record<string, AdvancedScalar>;
}

export const isEnterprise = (env: EnvType): boolean =>
  env === "enterprise-prod" || env === "enterprise-lab";
