// Extracts helm-docs style `# -- description` comments from the official
// Testkube chart values.yaml files and emits a typed tips map keyed by the
// dotted value path. These tips are surfaced in the wizard's "Customize"
// panels so users get the exact guidance from the upstream charts.
//
// Usage: node scripts/extract-tips.mjs
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..", "..");

const SOURCES = {
  oss: resolve(repoRoot, "testkube-helm-charts/charts/testkube/values.yaml"),
  enterprise: resolve(
    repoRoot,
    "testkube-cloud-charts/charts/testkube-enterprise/values.yaml"
  ),
};

const KEY_RE = /^(\s*)([A-Za-z0-9_."\-]+):(\s|$)/;

function parse(file) {
  const text = readFileSync(file, "utf8");
  const lines = text.split("\n");
  const tips = {};
  const stack = []; // { indent, key }
  let doc = null; // string[] | null
  let collecting = false;

  for (const raw of lines) {
    const line = raw.replace(/\s+$/, "");
    const trimmed = line.trim();

    if (trimmed === "") {
      doc = null;
      collecting = false;
      continue;
    }

    if (trimmed.startsWith("#")) {
      const afterHash = trimmed.replace(/^#+\s?/, "");
      if (afterHash.startsWith("-- ") || afterHash === "--") {
        doc = [afterHash.replace(/^--\s?/, "")];
        collecting = true;
      } else if (collecting && doc) {
        doc.push(afterHash);
      }
      continue;
    }

    const m = line.match(KEY_RE);
    if (m) {
      const indent = m[1].length;
      const key = m[2].replace(/"/g, "");
      while (stack.length && stack[stack.length - 1].indent >= indent) {
        stack.pop();
      }
      stack.push({ indent, key });
      const path = stack.map((s) => s.key).join(".");
      if (doc) {
        const desc = doc.join(" ").trim();
        if (desc) tips[path] = desc;
      }
    }
    // Any non-comment, non-blank line ends a doc block.
    doc = null;
    collecting = false;
  }
  return tips;
}

const out = {};
for (const [name, file] of Object.entries(SOURCES)) {
  if (!existsSync(file)) {
    console.warn(`[extract-tips] missing source: ${file}`);
    out[name] = {};
    continue;
  }
  out[name] = parse(file);
  console.log(
    `[extract-tips] ${name}: ${Object.keys(out[name]).length} tips from ${file}`
  );
}

const banner =
  "// AUTO-GENERATED by scripts/extract-tips.mjs — do not edit by hand.\n" +
  "// Source: official Testkube chart values.yaml (helm-docs `# --` comments).\n";

const body =
  banner +
  "export type TipMap = Record<string, string>;\n\n" +
  `export const ossTips: TipMap = ${JSON.stringify(out.oss, null, 2)};\n\n` +
  `export const enterpriseTips: TipMap = ${JSON.stringify(
    out.enterprise,
    null,
    2
  )};\n`;

const dest = resolve(__dirname, "..", "src/lib/tips.generated.ts");
writeFileSync(dest, body);
console.log(`[extract-tips] wrote ${dest}`);
