// Generates a local Enterprise values.yaml using the same generator as the UI.
// Run: npx tsx scripts/gen-local-sso.ts
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { generateYaml } from "../src/lib/yaml";
import { defaultConfig } from "../src/lib/defaults";
import type { TestkubeConfig } from "../src/types/config";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(__dirname, "..", "samples");
mkdirSync(outDir, { recursive: true });

const LICENSE = "66B620-0F58A8-B53956-5D98BA-EB5530-V3";

const cfg: TestkubeConfig = {
  ...defaultConfig,
  initial: {
    ...defaultConfig.initial,
    companyName: "Local Lab",
    adminEmail: "admin@example.com",
    envType: "enterprise-lab",
    licenseMode: "online",
    licenseKey: LICENSE,
    orgsEnvs: [{ id: "org-1", organization: "demo", environment: "my-first-environment" }],
  },
  endpoints: {
    ...defaultConfig.endpoints,
    domain: "",
    useKubernetesService: true,
    certManager: false,
  },
};

writeFileSync(resolve(outDir, "enterprise-local-sso.yaml"), generateYaml(cfg));

writeFileSync(
  resolve(outDir, "enterprise-local-secrets.yaml"),
  `# Secrets are auto-generated by sharedSecretGenerator during helm install.
# This file is kept for reference only — you do NOT need to apply it when
# using the generated values.yaml from the Testkube Initializer.
#
# If you prefer to pre-create secrets manually, disable sharedSecretGenerator
# in values.yaml and apply manifests like these instead:
---
apiVersion: v1
kind: Secret
metadata:
  name: testkube-minio-credentials
type: Opaque
stringData:
  root-user: "minio"
  root-password: "minio123"
  token: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: testkube-credentials-master
type: Opaque
stringData:
  password: "local-master-password-change-me"
---
apiVersion: v1
kind: Secret
metadata:
  name: testkube-default-agent-token
type: Opaque
stringData:
  token: "local-agent-token-change-me"
`
);

console.log("Wrote samples/enterprise-local-sso.yaml and samples/enterprise-local-secrets.yaml");
