// Generates plug-and-play values.yaml for each flavor exactly as the wizard
// would, for deployment on a local kind cluster.
//
// Run: npx tsx scripts/gen-kind-deploy.ts
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { generateYaml } from "../src/lib/yaml";
import { defaultConfig } from "../src/lib/defaults";
import type { TestkubeConfig } from "../src/types/config";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(__dirname, "..", "deploy");
mkdirSync(outDir, { recursive: true });

const LICENSE = "66B620-0F58A8-B53956-5D98BA-EB5530-V3";

const identity = {
  companyName: "Acme Corp",
  adminEmail: "admin@acme.com",
};

// --- OSS: in-cluster access (kind / port-forward) ---
const oss: TestkubeConfig = {
  ...defaultConfig,
  initial: { ...defaultConfig.initial, ...identity, envType: "oss" },
  endpoints: {
    ...defaultConfig.endpoints,
    domain: "",
    useKubernetesService: true,
    certManager: false,
  },
};

// --- Enterprise Lab: in-cluster access, online license ---
const lab: TestkubeConfig = {
  ...defaultConfig,
  initial: {
    ...defaultConfig.initial,
    ...identity,
    envType: "enterprise-lab",
    licenseMode: "online",
    licenseKey: LICENSE,
  },
  endpoints: {
    ...defaultConfig.endpoints,
    domain: "",
    useKubernetesService: true,
    certManager: false,
  },
};

// --- Enterprise Production: Ingress + domain (nip.io for kind), cert-manager
//     off because kind has no public DNS for Let's Encrypt. ---
const production: TestkubeConfig = {
  ...defaultConfig,
  initial: {
    ...defaultConfig.initial,
    ...identity,
    envType: "enterprise-prod",
    licenseMode: "online",
    licenseKey: LICENSE,
  },
  endpoints: {
    ...defaultConfig.endpoints,
    domain: "testkube.127.0.0.1.nip.io",
    useKubernetesService: false,
    certManager: false,
  },
};

// --- Enterprise Lab + AI: validates the new inference + PostgreSQL wiring ---
const labAi: TestkubeConfig = {
  ...lab,
  core: { ...lab.core, ai: true },
  ai: {
    ...defaultConfig.ai,
    provider: "openai",
    agentModel: "gpt-4o",
    credentialSource: "secret",
    apiKeySecretRef: "testkube-ai-llm",
    apiKeySecretKey: "apiKey",
    postgresMode: "in-cluster",
  },
};

// --- Enterprise Lab + SeaweedFS: validates in-cluster SeaweedFS storage ---
const labSeaweed: TestkubeConfig = {
  ...lab,
  artifacts: {
    ...lab.artifacts,
    type: "seaweedfs",
    external: false,
    connectionMode: "autogenerated",
    seaweedfsReleaseName: "tk-sw",
  },
};

// --- Enterprise Production + Gateway API: validates HTTPRoute exposure ---
const prodGateway: TestkubeConfig = {
  ...production,
  endpoints: {
    ...production.endpoints,
    exposureMode: "gateway",
    gatewayClassName: "traefik",
    gatewayCreate: true,
  },
};

const files: [string, TestkubeConfig][] = [
  ["oss.yaml", oss],
  ["lab.yaml", lab],
  ["production.yaml", production],
  ["lab-ai.yaml", labAi],
  ["lab-seaweed.yaml", labSeaweed],
  ["prod-gateway.yaml", prodGateway],
];

for (const [name, cfg] of files) {
  writeFileSync(resolve(outDir, name), generateYaml(cfg));
  console.log(`Wrote deploy/${name}`);
}
